### ISSUE TITLE
Cannot find preset's package (group:ngxs-storeMonorepo)

### ISSUE THREAD

**Issue by thib3113** [renovatebot/docker-renovate-full#11]
**What Renovate type are you using?**

Self hosted, with docker image :
```
{
  "tag": "renovate/renovate:latest",
  "checksum": "sha256:77b87b9e0a1a1e951f86a6ffdb96e65d99d65236d9708c3a816c1565f6e840a0",
  "Labels": {
    "maintainer": "Rhys Arkins <rhys@arkins.net>",
    "name": "renovate",
    "org.opencontainers.image.licenses": "AGPL-3.0-only",
    "org.opencontainers.image.source": "https://github.com/renovatebot/renovate",
    "org.opencontainers.image.url": "https://renovatebot.com",
    "org.opencontainers.image.version": "19.221.0-slim"
  }
}
```

**Describe the bug**

When starting the scan, I got a bug directly.

**Did you see anything helpful in debug logs?**
here is the full log : 
```
 INFO: Throwing preset error
FATAL: Fatal error: config-validation
       "err": {
         "validationError": "Cannot find preset's package (group:ngxs-storeMonorepo). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "_vGZdcQGi",
           "err": {
             "validationError": "Cannot find preset's package (group:ngxs-storeMonorepo). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
             "message": "config-validation",
             "stack": "Error: config-validation\n    at resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
           },
           "msg": "Fatal error: config-validation"
         }
       ]
```

**To Reproduce**

Doesn't really know, here is my configuration : 
```
module.exports = {
    platform: 'gitlab',
    endpoint: 'https://gitlab.private.com/api/v4/',
    assignees: ['thib3113'],
    baseBranches: ['dev'],
    labels: ['renovate'],
    extends: ['config:base'],
    npmrc: 'registry=http://npm.private.lan:4873',
    logLevel: 'debug'
};
```
My tokens for gitlab and github are set ( maybe you have an idea how to test ? an endpoint ? )

**Additional context**

**Comment by fastman** [comment]
Looks like now there's a new, similar error:
```
FATAL: Fatal error: config-validation
       "err": {
         "validationError": "Cannot find preset's package (config:base)",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "AXXRwvT9w",
           "err": {
             "validationError": "Cannot find preset's package (config:base)",
             "message": "config-validation",
             "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
           },
           "msg": "Fatal error: config-validation"
         }
       ]
```

**Comment by viceice** [comment]
Please wait for > 19.221.1 release

**Comment by thib3113** [comment]
@fastman not really . (config.base) seems to be like this : https://github.com/renovatebot/renovate/issues/6076

Did you configure GITHUB_COM_TOKEN ?

**Comment by viceice** [comment]
token is not needed with > 19.221.1

**Comment by thib3113** [comment]
oh ok . 

finally, 19.221.2 is available, but doesn't work : 
```
FATAL: Fatal error: platform-failure
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:31:19)\n    at getPresetFromEndpoint (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:80:29)\n    at Object.getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:94:12)\n    at getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:141:58)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:194:43)\n    at Object.parseConfigs (/usr/src/app/node_modules/renovate/dist/config/index.js:48:40)\n    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/node_modules/renovate/dist/renovate.js:16:24"
       }
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "JF-fiqaGd",
           "err": {
             "message": "platform-failure",
             "stack": "Error: platform-failure\n    at fetchJSONFile (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:31:19)\n    at getPresetFromEndpoint (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:80:29)\n    at Object.getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/github.js:94:12)\n    at getPreset (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:141:58)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:194:43)\n    at Object.parseConfigs (/usr/src/app/node_modules/renovate/dist/config/index.js:48:40)\n    at async Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/node_modules/renovate/dist/renovate.js:16:24"
           },
           "msg": "Fatal error: platform-failure"
         }
       ]
```

image : 
```
{
  "tag": "renovate/renovate:slim",
  "checksum": "sha256:13f99cf492e850b053fe829db449274dfbd3bdcdbf4f415ee06ebf9683dab848",
  "Labels": {
    "maintainer": "Rhys Arkins <rhys@arkins.net>",
    "name": "renovate",
    "org.opencontainers.image.licenses": "AGPL-3.0-only",
    "org.opencontainers.image.source": "https://github.com/renovatebot/renovate",
    "org.opencontainers.image.url": "https://renovatebot.com",
    "org.opencontainers.image.version": "19.221.2"
  }
}
```
( I move to slim, because full image is really huge ... I'll retry with image full )

**Comment by viceice** [comment]
if the slim image fails, the full fails too, because it is based on slim

**Comment by fastman** [comment]
> @fastman not really . (config.base) seems to be like this : [renovatebot/renovate#6076](https://github.com/renovatebot/renovate/issues/6076)
> 
> Did you configure GITHUB_COM_TOKEN ?
> 
> In my case (config:base) is loaded, and one of the sub config can't be loaded

yup, I have a GITHUB_COM_TOKEN  setup, but it doesn't seem to make any difference.

**Comment by viceice** [comment]
@rarkins Looks like there is something broken in renovate
