### ISSUE TITLE
renovate tries to install rust tool but lacks privileges

### ISSUE THREAD

**Issue by ilka-schulz** [renovatebot/docker-renovate-full#1108]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.40.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab 15.6.1-ee

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

A rust / cargo dependency (`clap`) was updated (`4.0.27` -> `4.0.28`) and Renovate produced an `Artifact update problem`:

```text
File name: Cargo.lock
Command failed: install-tool rust 1
This script must be run as root
```

### Relevant debug logs

<details><summary>Logs</summary>

```text
 INFO: Branch updated (repository=ees/warehouse/server, baseBranch=develop, branch=renovate/clap-4.x)
       "commitSha": "bdadcc47d8c2a9f3926b455e4acc4eb5ac2275f5"
 INFO: PR updated (repository=ees/warehouse/server, baseBranch=develop, branch=renovate/clap-4.x)
       "pr": 622,
       "prTitle": "fix(deps): update rust crate clap to 4.0.29"
 WARN: artifactErrors (repository=ees/warehouse/server, baseBranch=develop, branch=renovate/clap-4.x)
       "artifactErrors": [
         {
           "lockFile": "Cargo.lock",
           "stderr": "Command failed: install-tool rust 1.65.0\nThis script must be run as root\n"
         }
       ]
```
</details>

<details><summary>redacted debug logs</summary>

```text
DEBUG: Executing command (repository=ees/warehouse/server, baseBranch=develop, branch=renovate/clap-4.x)
       "command": "install-tool rust 1.65.0"
DEBUG: rawExec err (repository=ees/warehouse/server, baseBranch=develop, branch=renovate/clap-4.x)
       "err": {
         "name": "ExecError",
         "cmd": "/bin/sh -c install-tool rust 1.65.0",
         "stderr": "This script must be run as root\n",
         "stdout": "Installing v1 tool rust v1.65.0\n",
         "options": {
           "cwd": "/builds/IEMS/renovate/renovate/repos/gitlab/ees/warehouse/server",
           "encoding": "utf-8",
           "env": {
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.11.0/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.11.0/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "BUILDPACK_CACHE_DIR": "/builds/IEMS/renovate/renovate/cache/containerbase",
             "CONTAINERBASE_CACHE_DIR": "/builds/IEMS/renovate/renovate/cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "message": "Command failed: install-tool rust 1.65.0\nThis script must be run as root\n",
         "stack": "ExecError: Command failed: install-tool rust 1.65.0\nThis script must be run as root\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)"
       }
DEBUG: Failed to update Cargo lock file (repository=ees/warehouse/server, baseBranch=develop, branch=renovate/clap-4.x)
       "err": {
         "name": "ExecError",
         "cmd": "/bin/sh -c install-tool rust 1.65.0",
         "stderr": "This script must be run as root\n",
         "stdout": "Installing v1 tool rust v1.65.0\n",
         "options": {
           "cwd": "/builds/IEMS/renovate/renovate/repos/gitlab/ees/warehouse/server",
           "encoding": "utf-8",
           "env": {
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.11.0/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.11.0/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "BUILDPACK_CACHE_DIR": "/builds/IEMS/renovate/renovate/cache/containerbase",
             "CONTAINERBASE_CACHE_DIR": "/builds/IEMS/renovate/renovate/cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "message": "Command failed: install-tool rust 1.65.0\nThis script must be run as root\n",
         "stack": "ExecError: Command failed: install-tool rust 1.65.0\nThis script must be run as root\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)"
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
Bug in this image, it's still using an outdated `renovate/buildpack` image. will fix it now

https://github.com/renovatebot/docker-renovate-full/blob/6f9ffca1599bb3cf9c85e2ad32b0c264ff070a6f/Dockerfile#L6

**Comment by viceice** [comment]
Will need a couple of hours until all images are rebuild and pushed. latest version should be updated in around 15 min
