### ISSUE TITLE
Authentication failure when using Docker Image

### ISSUE THREAD

**Issue by gardebring** [renovatebot/docker-renovate-full#25]
Hi. I am having an issue with trying to run the docker image of renovate.
First some background: I have the renovate npm package installed on an ubuntu 18-server and this setup works fine with the same configuration and repository. However, when I use the same configuration with the docker image, I get an authentication failure.
Please note that I am running this towards an Azure Devops Server _on-premise_, **not** the Azure Devops Services cloud solution.

This is how I run the npm package from my Linux box:

`renovate --log-level debug --platform=azure --endpoint=https://azdevops-server.hostname/DefaultCollection --token=TOKEN ProjectName/RepositoryName`

This works as expected.

However, when I try to run the docker image (from a Windows 10 host set to Linux image mode) with the following command:

`docker run --rm -v "C:\Git\Customer\CustomerName\DockerRenovate\config.js:/usr/src/app/config.js" renovate/renovate`

With a config.js that looks like this:

```
module.exports = {
  endpoint: 'https://azdevops-server.hostname/DefaultCollection',
  token: 'TOKEN',
  platform: 'azure',
  logLevel: 'debug',
  repositories: ['ProjectName/RepositoryName'],
};
```

I get the following output:

```
DEBUG: File config
       "config": {
         "endpoint": "https://azdevops-server.hostname/DefaultCollection",
         "token": "***********",
         "platform": "azure",
         "logLevel": "debug",
         "repositories": ["ProjectName/RepositoryName"]
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "endpoint": "https://azdevops-server.hostname/DefaultCollection",
         "token": "***********",
         "platform": "azure",
         "logLevel": "debug",
         "repositories": ["ProjectName/RepositoryName"],
         "hostRules": []
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Using default gitAuthor: Renovate Bot <bot@renovateapp.com>
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Limits.init enter method
DEBUG: Limits.init prCommitsPerRunLimit processing
DEBUG: Limits.init prCommitsPerRunLimit variable is not set. Ignoring prCommitsPerRunLimit
 INFO: Repository started (repository=ProjectName/RepositoryName)
       "renovateVersion": "0.0.0-semantic-release"
DEBUG: Using localDir: /tmp/renovate/repos/azure/ProjectName/RepositoryName (repository=ProjectName/RepositoryName)
DEBUG: initRepo("ProjectName/RepositoryName") (repository=ProjectName/RepositoryName)
DEBUG: Repository details (repository=ProjectName/RepositoryName)
       "repositoryDetails": {
         "id": "f631827b-23c9-402e-a027-6f4cb32e6223",
         "name": "RepositoryName",
         "url": "https://azdevops-server.hostname/DefaultCollection/9e89e5ae-3577-4153-9c14-2b163fed8e45/_apis/git/repositories/f631827b-23c9-402e-a027-6f4cb32e6223",
         "project": {
           "id": "9e89e5ae-3577-4153-9c14-2b163fed8e45",
           "name": "ProjectName",
           "description": "Test for ProjectName",
           "url": "https://azdevops-server.hostname/DefaultCollection/_apis/projects/9e89e5ae-3577-4153-9c14-2b163fed8e45",
           "state": "wellFormed",
           "revision": 22,
           "visibility": 0
         },
         "defaultBranch": "refs/heads/master",
         "size": 152683,
         "remoteUrl": "https://azdevops-server.hostname/DefaultCollection/ProjectName/_git/RepositoryName",
         "sshUrl": "ssh://azdevops-server.hostname:22/DefaultCollection/ProjectName/_git/RepositoryName"
       }
DEBUG: ProjectName/RepositoryName owner = ?owner? (repository=ProjectName/RepositoryName)
DEBUG: ProjectName/RepositoryName default branch = master (repository=ProjectName/RepositoryName)
DEBUG: Initializing git repository into /tmp/renovate/repos/azure/ProjectName/RepositoryName (repository=ProjectName/RepositoryName)
DEBUG: git clone error (repository=ProjectName/RepositoryName)
       "err": {
         "message": "Cloning into '.'...\nfatal: Authentication failed for 'https://azdevops-server.hostname/DefaultCollection/ProjectName/_git/RepositoryName/'\n",
         "stack": "Error: Cloning into '.'...\nfatal: Authentication failed for 'https://azdevops-server.hostname/DefaultCollection/ProjectName/_git/RepositoryName/'\n\n    at toError (/usr/src/app/node_modules/simple-git/promise.js:90:14)\n    at /usr/src/app/node_modules/simple-git/promise.js:61:36\n    at Git.<anonymous> (/usr/src/app/node_modules/simple-git/src/git.js:214:18)\n    at Function.Git.fail (/usr/src/app/node_modules/simple-git/src/git.js:1475:18)\n    at fail (/usr/src/app/node_modules/simple-git/src/git.js:1433:20)\n    at /usr/src/app/node_modules/simple-git/src/git.js:1442:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Platform error - skipping (repository=ProjectName/RepositoryName)
 INFO: Repository finished (repository=ProjectName/RepositoryName)
DEBUG: Host request stats (milliseconds)
       "hostStats": {}
DEBUG: Renovate existing successfully
```

So, the npm package works fine, but it fails when running from docker.
I should also mention that the renovate me marketplace plugin (which also use the npm package) works fine as well.
The test project is a .NET Core project.

**Comment by viceice** [comment]
When do you pulled the `renovate/renovate` image?

` "renovateVersion": "0.0.0-semantic-release"` tolds me it's outdated, because it should print the current version

```
❯ docker run --rm renovate/renovate --version
19.239.3
```
